//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class persons
    {
        public int id { get; set; }
        public string username { get; set; }
        public Nullable<int> tz { get; set; }
        public string adress { get; set; }
        public string mail { get; set; }
        public string phone { get; set; }
        public string inqure { get; set; }
        public Nullable<int> ok { get; set; }
        public string password { get; set; }
    }
}
