//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class travels
    {
        public int id { get; set; }
        public Nullable<int> id_offer { get; set; }
        public Nullable<int> id_request { get; set; }
        public string resourse { get; set; }
        public string destination { get; set; }
        public Nullable<int> seats { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<double> price { get; set; }
    }
}
